index.html
react/features/base/react/components/web/Watermarks.js

[Jira issue](https://janeapp.atlassian.net/browse/TEL-186)
- Remove the "a" link from the top left jane watermark logo.
Resource: [Code Review Checklist](https://www.notion.so/janeapp/Code-Review-checklist-2c510c527ac7470c902a5e8f25f9db3c)
Click on the top left jane logo => should not redirect to jane.

[Tel-186] clicking logo in call opens marketing site

---

react/features/toolbox/components/web/Toolbox.js

- Disable screen-sharing feature in Electron by removing the `dekstop sharing` button in `ToolBox` component
Resource: [Code Review Checklist](https://www.notion.so/janeapp/Code-Review-checklist-2c510c527ac7470c902a5e8f25f9db3c)
- Join an online appointment in Jane Desktop
- the "share your screen" button should be invisible.

[TRON-57] Disable screen-sharing in Jane Desktop video-chat

---

react/features/base/conference/actions.js
webpack.config.js

I found a bug on bugsnag:
Solution:
- update the condition in `send leave beacon` code block in `conferenceWillLeave` action function.
Webpack update(not related to this bug):
- update the webpack config file and the webpack will only generate the index HTML file from the template when it is bundling the `app.js`. 
Resource: [Code Review Checklist](https://www.notion.so/janeapp/Code-Review-checklist-2c510c527ac7470c902a5e8f25f9db3c)
- Create an online appointment.
- Open browser dev tool > **Network**
- Click on the online appointment in the calendar
- Copy the links from here:
- Convert the link to `https` protocol like this:
`//videochat-jwt.jane.qa/.....` > …

Fix toISOString TypeError error when leaving meeting & update the webpack config

---

PULL_REQUEST_TEMPLATE.md

Pulled in some recent updates to the template in janeapp/jane
📜 Template Update
n/a
n/a
Zero risk
n/a
Resource: [Code Review Checklist](https://www.notion.so/janeapp/Code-Review-checklist-2c510c527ac7470c902a5e8f25f9db3c)
n/a
n/a

Update Pull Request Template

---

interface_config.js
modules/UI/videolayout/LocalVideo.js
modules/UI/videolayout/RemoteVideo.js

- [Jira Ticket](https://janeapp.atlassian.net/browse/TEL-294)
We were seeing high CPU utilization on some clients' machines. To resolve this issue we decided to disable/remove the following feature/settings:
- disabling H.264 codec (related to hardware acceleration) on the back-end side.
- disabling video backgrounds in FE.
- remove the `AudioLevelIndicator` component from `LargeVideo` & `RemoteVideo` component.
Low
Resource: [Code Review …

[TEL-294] Improve CPU Utilization to improve Telehealth experience(web)

---

react/features/analytics/AnalyticsEvents.js
react/features/analytics/functions.js
react/features/base/participants/functions.js
react/features/connection-indicator/statsEmitter.js

- [Linear Ticket](https://linear.app/jane/issue/IMPT-3/create-custom-events-and-property-for-sending-more-participants)
In order to measure the call quality and determine what might be causing issues in a call. We decided to add a custom amplitude event & a custom amplitude property to jitsi.
- Create a "connection.quality.changed" custom event to send local participant's connection statistics data to amplitude if the user's network connection strength changes.
- Add a `participantType` permanent property to identify the user type to all amplitude events.
> Describe here a CS friendly version of what this fixes/adds. If the change is behind a feature flag, please include that in your description. If this is a hidden change CS doesn't need to really know about …

[IMPT-3] Create custom events & property for sending more participant's statistics data to amplitude

---

conference.js
react/features/video-quality/middleware.js

[notion](https://www.notion.so/janeapp/Video-not-displaying-even-when-turned-on-c9a988f2d5df46888a7a02a834cfc40a)
Some participant will have their video on (can see themselves) but to the other participant, it will appear that their video is either off (shows initials) or is all black. (After the 5076 upgrade)
Jitsi updated their `lib-jitsi-meet` library code in August for the "layer suspension" feature. This update caused the app to stop encoding the sender's video track occasionally(can not get the sender video height properly.) if the app doesn't have the layerSuspension config option enabled.
more info: https://github.com/jitsi/lib-jitsi-meet/issues/1333#issuecomment-708513033
Set sender video constraint to 720 when user joining the conference to avoid the `null` sender video height …

[Fix] Video not displaying even when turned on

---

react/features/analytics/AnalyticsEvents.js
react/features/analytics/functions.js
react/features/base/participants/functions.js
react/features/connection-indicator/statsEmitter.js

- [Linear Ticket](https://linear.app/jane/issue/IMPT-3/create-custom-events-and-property-for-sending-more-participants)
In order to measure the call quality and determine what might be causing issues in a call. We decided to add a custom amplitude event & a custom amplitude property to jitsi.
- Create a "connection.quality.changed" custom event to send local participant's connection statistics data to amplitude if the user's network connection strength changes.
- Add a `participantType` permanent property to identify the user type to all amplitude events.
> Describe here a CS friendly version of what this fixes/adds. If the change is behind a feature flag, please include that in your description. If this is a hidden change CS doesn't need to really know about …

[IMPT-3, IMPT-353][IOS] Create custom events & property for sending more participant's statistics data to amplitude

---

ios/Podfile
ios/Podfile.lock
ios/app/app.xcodeproj/project.pbxproj
ios/app/src/AppDelegate.m
ios/app/src/GoogleService-Info.plist
ios/app/src/Info.plist
ios/app/src/ViewController.m

- [Jira Ticket](https://janeapp.atlassian.net/browse/TEL-293)
Because The Fabric SDK is now deprecated and will not continue reporting the app's crashes.
I removed the Fabric SDK and added the latest Firebase Crashlytics SDK to the app by following the [guides.](https://firebase.google.com/docs/crashlytics/get-started?platform=ios&authuser=0#add-sdk)
> 3. Medium or higher risk PRs should get more than one code-review …

[IMPT-46] Update Crashlytics

---

react/features/connection-indicator/statsEmitter.js

We're hitting our Amplitude event limit and most are coming form the connection quality event. Let's reduce what we're collecting so we only send the connection.quality.changed event if it is poor. This would still allow us to see when users have a poor connection. 
[Linear ticket](https://linear.app/jane/issue/IMPT-398/only-send-the-poor-connection-events-to-amplitude)
N/A
> 3. Medium or higher risk PRs should get more …

[IMPT-398] Only send the Poor connection events to Amplitude

---

react/features/connection-indicator/statsEmitter.js

We're hitting our Amplitude event limit and most are coming form the connection quality event. Let's reduce what we're collecting so we only send the connection.quality.changed event if it is poor. This would still allow us to see when users have a poor connection. 
[Linear ticket](https://linear.app/jane/issue/IMPT-398/only-send-the-poor-connection-events-to-amplitude)
N/A
> 3. Medium or higher risk PRs should get more …

[IMPT-398][IOS] Only send the Poor connection events to Amplitude

---

modules/UI/videolayout/LargeVideoManager.js
modules/UI/videolayout/VideoContainer.js

- [Linear Ticket](https://linear.app/jane/issue/IMPT-362/pad-the-video-so-it-can-be-a-max-of-n-pixels)
We want to pad the video for SD so we can maintain the video pixel density and it won't look blurry when users maximize the video call window. The padding will be only added to desktop & tablet browsers. 
- add 10% padding for all four sides of the SD video container only. (not for the HD)
- only add padding if the screen width > 768px (for tablet & desktop device)
> 2. Unless exempt, checked risk factors should be explained comprehensively …

[IMPT-362] Pad the video so it can be a max of N pixels

---

modules/UI/videolayout/LargeVideoManager.js

- [Linear Ticket](https://linear.app/jane/issue/SCH-262/telehealth-chat-panel-moves-the-video-out-of-the-screen)
Issue:
When users pop out the chat panel, the video layout got right sided position. When the chat is closed, Video does not return to its original location.
Solution:
- When updating the video container. If the chat state is open, re-compute the container width by subtracting the default width of the chat. …

[SCH-262] Fix: Chat panel moves the video out of the screen

---

conference.js
css/_hd-video-alert.scss
css/main.scss
react/features/base/tracks/functions.js
react/features/conference/components/AbstractConference.js
react/features/conference/components/web/Conference.js
react/features/connection-indicator/statsEmitter.js
react/features/notifications/actionTypes.js
react/features/notifications/actions.js
react/features/notifications/components/web/HdVideoAlert.js
react/features/notifications/reducer.js
react/features/toolbox/components/web/Toolbox.js

- [Linear Ticket](https://linear.app/jane/issue/SCH-263/telehealth-hd-video-quality-alert)
- [Slack](https://janeapp.slack.com/archives/CTQRM510Q/p1614973707006800)
Since we want to prompt practitioners to enable the HD video beta feature in Jitsi only if they have a good connection. This PR updates the HD video loading flow as below:
- Adds an HD video alert component.
- Adds a new HD video constrain setting to keep the HD video full screen since we've added padding to the SD video.
- Limit the video quality to HD(360) when initiating the call.
- Detects the actual connection quality strength in `_onStatsUpdated` listener and shows the `HD video quality alert` only if the practitioner has a "good" connection (connection quality strength > 30, bandwidth bitrate > 2500kps).
- Only allows …

[SCH-263] HD video quality alert

---

react/features/chat/components/AbstractChatMessage.js

- [Linear Ticket](https://linear.app/jane/issue/IMPT-41/use-the-time-format-from-jane)
- Replace the military time format with the 12-hour system format in private chat.
Use the time format from Jane in the private chat.
N/A
>
<sup>1</sup> No need to explain these …

[IMPT-41] Use the time format from Jane

---

lang/main.json

- [Linear Ticket](https://linear.app/jane/issue/SCH-301/make-language-consistent-in-waiting-room-ui)
- Change the word "patient" to "client" to match the "client is waiting" badge in waiting room modal. 
>
> …

[SCH-301] Make language consistent in Waiting Room UI

---

Dockerfile

The key will be provided via the build environment. 
https://github.com/janeapp/terraform-prod/pull/317

Docker: Inject bugsnag api key from env before compiling

---

docker-configs/nginx/nginx.conf

These changes let us log real client IP addresses in datadog, instead of the intermediary Amazon Load Balancer IP.

Log real client IPs in nginx container

---

lang/main-enGB.json
lang/main-id.json
lang/main.json
react/features/notifications/components/web/Notification.js

- [Linear Ticket](https://linear.app/jane/issue/SCH-322/update-the-authentication-failed-error-modal-in-jitsi)
We noticed that the contact support button in the "authentication failed" error notification modal redirects users to jitsi community forum which is not ideal. 
After discussing with Julia & Ramineh we decided to remove the contact support button from the error notification and update the original message copy to `Please try accessing your session again and reach out to the clinic for help. `
This PR:
- Remove the "contact button" from the notification component by setting the `hideErrorSupportLink` param to true.
- Update the `tokenAuthFailed` message 
Updated the "authentication failed" error notification in jitsi.
N/A
> 1. As the author you should check …

[SCH-322] Update the "authentication failed" error notification in jitsi

---

app.js
conference.js
react/features/always-on-top/HangupButton.js
react/features/app/actions.js
react/features/base/util/helpers.js
react/features/jane-waiting-area/components/SocketConnection.web.js
react/features/jane-waiting-area/components/dialogs/JaneDialog.js
react/features/jane-waiting-area/functions.js
react/features/toolbox/components/JaneHangupButton.js

- [Linear](https://linear.app/jane/issue/SCH-340/video-chat-app-sends-left-waiting-room-signal-twice-to-jane-when-users)
The web app sends the "left waiting room" signal multiple times (twice) to the `/video_chat_sessions/update_participant_status` endpoint when a user hangs up the call. 
We want the web app to send the "left" waiting room signal to Jane after a user clicks the `hangup` button or closes the browser window directly. Although the `hangup` handler function will also execute the `window.close()` to close the browser window and this might trigger the `window.beforeunload` & `window.unload` callbacks. However, I noticed that sometimes those callbacks are not guaranteed to be executed. So I have to place the sending `left` signal action in those callbacks and the `hangup` …

[SCH-340] Video chat web app sends "left waiting room" signal twice to Jane when user hangs up the call

---

lang/main.json
react/features/jane-waiting-area/components/JaneWaitingArea.js
react/features/jane-waiting-area/components/modal/Modal.js

- [Linear Ticket](https://linear.app/jane/issue/SCH-388/remove-begin-button-from-patient-waiting-room)
- A follow-up PR for SCH-373
- Remove the Begin button from the Patient's side of the Waiting Room & update the Modal UI for android devices.
- Once the practitioner allows the patient in by clicking the `Admit client` button, the patient in the waiting room will join the call directly.
https://www.loom.com/share/eb572193c9524defbf53183906bb0974
> 2. Unless exempt, checked risk factors should be explained comprehensively in the Release Risk …

[SCH-388][Web app] Remove Begin Button from Patient Waiting Room 

---

modules/UI/videolayout/VideoContainer.js

- [Slack](https://janeapp.slack.com/archives/C0109LT2A3S/p1622233211044700)
- [Helpscout](https://secure.helpscout.net/conversation/1525390447/527754?folderId=4067769)
Issue: a clinic is having issues with video quality: there is a strange line just off the center of the screen and leaves to contrasting brightness shades.
Solution:
Round the width & height of the video when calculating the video container dimensions, 
Fixed the strange contrasting brightness shades issue
> 2. Unless exempt, checked risk factors should be explained …

[Fix] strange contrasting brightness shades in the video

---

modules/UI/videolayout/VideoContainer.js

[Linear](https://linear.app/jane/issue/SCH-460/telehealth-video-is-zooming-in-and-out-during-call)
[Slack](https://janeapp.slack.com/archives/C0109LT2A3S/p1629992033003600)
Although we are not able to reproduce this bug, I believe it's an edge case that occurs when one of the participants is using chrome on an android tablet (portrait mode) and encounters a bad network connection. the video height could be automatically reduced below 360 by Jitsi, causes the `getMaxZoomCoefficient` function to return different values during the change, resulting in a zoom-in/zoom-out effect on another participant's video screen (using a desktop).
Solution:
- Do not apply paddings & only return the default `MAXIMUM_ZOOMING_COEFFICIENT` value for the remote mobile video tracks. …

[SCH-460] Telehealth video is zooming in and out during call (web app)

---

react/features/jane-waiting-area/components/dialogs/JaneDialog.js

- [Linear Ticket](https://linear.app/jane/issue/SCH-393/display-treatment-length-not-scheduled-length-in-appointment-moda)
- A follow-up PR for LANG-19
- In the waiting room modal, use `treament_duration` from jwt payload in priority to calculate the treatment length.
[Demo Video](https://www.loom.com/share/a8590f4a215042b0a0ae969178d301b1)
>
> …

[SCH-393][Web app] Display Treatment length not scheduled length in Appointment Modal

---

react/features/jane-waiting-area/components/native/DialogBox.js

- [Linear Ticket](https://linear.app/jane/issue/SCH-388/remove-begin-button-from-patient-waiting-room)
- Remove the Begin button from the Patient's side of the Waiting Room & update the Modal UI.
- Once the practitioner allows the patient in by clicking the `Admit client` button, the patient in the waiting room will join the call directly.
https://www.loom.com/share/53a4c538b0e44550bef36fb6042098dc
> 3. Medium or higher …

[SCH-388][iOS] Remove Begin Button from Patient Waiting Room

---

css/_jane-waiting-area.scss

- At a particular window size, it is possible that the user will not be able to click the "admit" button due to the hidden component's occlusion.
Solution: increase the z-index of the waiting room modal
> …

Increase the z-index of the waiting room modal

---

react/features/analytics/AnalyticsEvents.js
react/features/jane-waiting-area/components/SocketConnection.web.js
react/features/jane-waiting-area/components/modal/Modal.js

- [Linear](https://linear.app/jane/issue/SCH-525/analytics-events-to-track-waiting-rooms-socket-message-and-admit)
- use `createWaitingAreaSocketEvent` & `createWaitingAreaModalEvent` events to track socket messages sent from Jane & the admit button actions in the waiting room modal
>
> NOTE: if you aren't changing any production files, please use …

[SCH-525][Web app] Analytics events to track waiting room socket message and admit button actions

---

docker-configs/nginx/nginx.conf

This enables nginx stats, which Datadog will be able to collect.

Enable the nginx stub_status endpoint for datadog monitoring

---

docker-configs/templates/config.js.j2

Adding `enableUnifiedOnChrome: true` just to be explicit (it seems to default to it on latest jitsi build)
Also disabling some unwanted features.
I tried setting minimum height constraint to 90 instead of 180, but in testing I couldn't get it to go any lower than 180, so I reverted it.

Update config js

---

react/features/base/conference/actions.js

- [Linear](https://linear.app/jane/issue/SCH-736/online-appointments-and-activity-report-is-not-recording-in-the-online)
This PR fixes an issue that the iOS app is not sending the duration of the session to Jane.
- Obtain the correct conference "start" time variable from the "conference" reducer in order to send it to Jane when participants leave the session 
> 3. Medium or higher risk PRs should get more than one …

[SCH-736][iOS] Online Appointments and Activity report is not recording in the Online Appointments Report

---

docker-configs/templates/config.js.j2

Changes the internal domain name from `meet.jitsi` to `meet.jane`
The domain may be visible in parts of the UI
Deploy at the same time as the other updates services (jicofo, prosody, jvb, nginx websocket, nginx app)
https://github.com/janeapp/jitsi-jicofo/pull/7
https://github.com/janeapp/jitsi-jvb/pull/5
https://github.com/janeapp/jitsi-prosody/pull/6
https://github.com/janeapp/jitsi-nginx/pull/7
https://github.com/janeapp/video-chat/pull/115
Revert, make a new build, and deploy it along with reverted builds of the other services
[PLA-1374](https://linear.app/jane/issue/PLA-1374/change-nginx-app-domain-name)
Low risk. Could break jitsi, but it's not in production yet.
Make sure the containers still start and we can open a conference.

Change domain name from meet.jitsi to meet.jane [PLA-1374]

---

react/features/jane-waiting-area/components/native/DialogBox.js
react/features/jane-waiting-area/components/web/modal/Modal.js

- [Linear Ticket](https://linear.app/jane/issue/SCH-630/display-the-treatment-start-time-end-time-and-duration-of-the)
This PR includes fixes for iOS app and web app:
- Calculate the end time of the appointment in the waiting room modal by adding the treatment duration to the start time
>
> NOTE: if you aren't changing any production files, …

[SCH-630][Web][iOS] Display the Treatment End Time of the Appointment in Waiting Room Modal 

---

ios/app/app.entitlements
ios/app/src/AppDelegate.m
react/features/base/known-domains/reducer.js
react/features/base/util/uri.js

- [Linear Ticket](https://linear.app/jane/issue/SCH-850/add-new-universal-links-to-ios-app)
- add new universal link domains to the ios app.
>
Should be low, just adding new domains to the ios app
Resource: …

[SCH-850] add new universal link domains to the ios app.

---

react/features/analytics/AnalyticsEvents.js
react/features/jane-waiting-area/middleware.js

- [Linear Ticket](https://linear.app/jane/issue/SCH-885/add-minimize-events-to-datadog-to-indicate-the-activity-has-moved-to)
- Creates an "app.state.changed" event to indicate if the app is in the foreground or background.
- Sends this event to datadog if the "appstate" has changed.
>
> NOTE: if you aren't changing any production files, please use …

[SCH-885] Add minimize events to Datadog to indicate the activity has moved to the background

---

react/features/jane-waiting-area/components/native/DialogBox.js
react/features/jane-waiting-area/constants.js
react/features/jane-waiting-area/functions.js

We noticed a rare edge case( one [report](https://janeapp.slack.com/archives/C0109LT2A3S/p1634581288216800) from support team so far). A user launched Jane online appointments ios app from the `Apple Mail app` and the socket bridge web view page could not be loaded properly when initializing the waiting room component. As we're not able to reproduce this issue. My guess is that it was probably because the ios system was blocking the page due to some security/privacy reasons and oddly this didn't trigger the `onError` callback of the Webview component as well.
Since the `onError` listener is unable to detect whether the webview page is fully loaded, I decided to use `onLoadEnd` and `onLoadStart` listener to monitor the loading status of the page, if it doesn't finish loading within 10 …

[Fix][iOS] Polling fallback for Socket webview page when the page fails to load.

---

css/_jane-waiting-area.scss
react/features/jane-waiting-area/components/web/preview/Preview.js

- [Linear Ticket](https://linear.app/jane/issue/SCH-817/waiting-room-brightness-has-a-darkness-overlay-added-to-it)
- Remove redundant preview overlay elements from the waiting room "Preview" component
>
Risk …

[SCH-817] Waiting room brightness has a darkness overlay added to it

---

docker-configs/templates/config.js.tmpl

Adds `useStunTurn: true` outside of p2p block, so turn servers can also be used for JVB calls.  However, it will not relay UDP connections to the JVB since the JVB can already do that.
For TCP, the JVB is much less efficient than the turn server, so if client's UDP is blocked, they can connect to TURN via TCP and that relays to JVB over UDP.

Use turn servers for jvb connections (tcp only)

---

ios/app/src/Info.plist

- [Linear Ticket](https://linear.app/jane/issue/SCH-968/online-appointments-on-ipad-arent-able-to-be-put-in-landscape-mode)
- Allow rotation(landscape mode) while keeping the app running full-screen on iPad
- Keep "portrait mode only" setting for iPhone
> …

[SCH-968][iOS] Online Appointments on iPad aren't able to be put in landscape mode

---

docker-configs/templates/config.js.tmpl
react/features/audio-level-indicator/components/AudioLevelIndicator.js

- Set `disableAudioLevels` option to false to enable the audio level bar in the audio setting pane.
- Since this option is enabled, we also need to stop rendering the AudioLevelIndicator component in order to reduce CPU usage.

Enable audio level in config.js

---

react/features/base/jwt/functions.js
react/features/overlay/components/AbstractPageReloadOverlay.js

- [Linear Ticket](https://linear.app/jane/issue/PAT-1106/prevent-jitsi-from-automatically-refreshing-the-page-after-ending-a)
- Adds `isJwtTokenExpired` function to determine if jwt has expired
- Prevent `PageReloadOverlay` from continuously reloading the page automatically if jwt has expired.
Low Risk
1. Create an jitsi online appt
2. Copy and paste the JWT from the video chat url onto jwt.io, and modify its expiration time to make it expire.
3. Use the expired jwt to open Jitsi app
4. We should see a error notification pops up and `connection` related errors in the console
5. wait for a few minutes, and Jitsi app should no longer automatically reload the page after showing the jwt or connection-related errors.
extra QA: we probably need a smoke test to ensure this PR won't break …

[PAT-1106] Prevent Jitsi from automatically refreshing the page after ending a session.

---

.github/workflows/auto_create_linear_issues_for_dependabot.yml
.github/workflows/keep_sec_cve_issues_in_sync_with_child_issues.yml

This PR adds two github actions to this Repository to automatically create linear issues for security vulnerabilities detected by Dependabot and also keeps the state and priorities of the child tickets in sync with their parent tickets.

add github actions to repo to create and manage SEC CVE issues

---

react/features/connection-stats/components/ConnectionStatsTable.js

Remove mentions of local and remote user IP addresses and ports when users hover over their connection status indicator > more menu option. See before/after screenshots
https://jira-jane.atlassian.net/browse/PAT-1291
Low Risk
N/A
- Verify IP addresses and ports do not show up in waiting room or in the call
- Just a smoke test on s5
N/A
Before / after of connection status info in the Waiting Room
Before / after of connection status info when users have joined a session

[PAT-1291] Remove mentions of IP addresses and ports numbers from connection stats overlay

---

package-lock.json
package.json

- [Jira Ticket](https://jira-jane.atlassian.net/jira/software/c/projects/PAT/boards/53?selectedIssue=PAT-1148)
- Bump moment version to 2.29.4
Low Risk
Smoke test
> - Will this affect other parts of the app or views?
> - How can the success of this work be confirmed after release to production?
> - What QA have you already done?

[PAT-1148] CVE-2022-31129: moment Upgrade to >= 2.29.4

---

package.json
react/features/analytics/handlers/JaneHandler.js
react/features/app/functions.native.js
react/features/app/functions.web.js
version_release.sh
webpack.config.js

- [Jira Ticket](https://jira-jane.atlassian.net/browse/PAT-1371)
- Adds release script
- Adds app client version to the webpack config script & analytics event
Low Risk
- Run the command: `sh version_release.sh`. This should generate a release PR and automatically increment the version number.
- Ensure that the analytics event parameters include the app_version field.
> - Will this affect other parts of the app or views?
> - How can the success of this work be confirmed after release to production?
> - What QA have you already done?

[PAT-1371] add release script & app version

---

react/features/base/jwt/functions.js
react/features/base/react/components/native/PreCallMessage.js
react/features/jane-waiting-area/actions.js
react/features/jane-waiting-area/components/SocketConnection.js
react/features/jane-waiting-area/components/native/DialogBox.js
react/features/jane-waiting-area/functions.js

Updates the iOS UI to fetch Jane appointment details (treatment, treatment duration, start at + end at times and practitioner name) from state
https://jira-jane.atlassian.net/browse/PAT-1383
Low-med risk since iOS is harder to test
N/A
1. Book an appointment and start a call
2. Ensure users can see the treatment information on the left side panel and modal in the waiting area with without PHI in JWT
4. Smoke test major features
5. Test in TestFlight and test the web app version of Jitsi as changes were made
> - Will this affect other parts of the app or views?
Both the iOS version and the web app version of Jitsi
> - How can the success of this work be confirmed after release to production?
- Must test on production once it is deployed to UK pod and join the call using an iOS device and …

[PAT-1383] Update iOS UI
